// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPlGPTYMImEvFxXLto9tmczvmcKKnggYI',
    appId: '1:841801292801:web:fe23f2aac981354239b400',
    messagingSenderId: '841801292801',
    projectId: 'alarrm-app',
    authDomain: 'alarrm-app.firebaseapp.com',
    storageBucket: 'alarrm-app.appspot.com',
    measurementId: 'G-DWGWCCYJXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd_cpGJOyjLEms2qcYtcMO7LsjWkZxBUQ',
    appId: '1:841801292801:android:3457884e9557497c39b400',
    messagingSenderId: '841801292801',
    projectId: 'alarrm-app',
    storageBucket: 'alarrm-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8dcv4sf9l36crkOz4IdAQQi4_XdsE4hs',
    appId: '1:841801292801:ios:1fc1ffc6d0ee8d0539b400',
    messagingSenderId: '841801292801',
    projectId: 'alarrm-app',
    storageBucket: 'alarrm-app.appspot.com',
    iosBundleId: 'com.example.alarmApp',
  );
}
